# Generated by Django 4.1.4 on 2023-01-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="audio",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="coverArt",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="team",
            name="picture",
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
