# Generated by Django 4.1.4 on 2023-02-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_team_picturethumb"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="picture",
        ),
        migrations.AlterField(
            model_name="podcast",
            name="coverArt",
            field=models.ImageField(
                blank=True, default="defaultCover.png", upload_to=""
            ),
        ),
    ]
