# Generated by Django 4.1.4 on 2023-02-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_team_picture_alter_podcast_coverart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="audio",
            field=models.FileField(blank=True, default="default.mp3", upload_to=""),
        ),
    ]
