# Generated by Django 4.1.4 on 2023-02-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                (
                    "coverArt",
                    models.ImageField(
                        blank=True, default="defaultCover.png", upload_to=""
                    ),
                ),
                ("description", models.CharField(max_length=400)),
                (
                    "audio",
                    models.FileField(blank=True, default="default.mp3", upload_to=""),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("coHost", models.CharField(default=None, max_length=50)),
                ("host", models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("aboutText", models.CharField(max_length=500)),
                (
                    "pictureThumb",
                    models.ImageField(blank=True, default="default.png", upload_to=""),
                ),
            ],
        ),
    ]
